version: '3'
services:
  frontend:
    container_name: frontend
    image: ${CI_REGISTRY_IMAGE}/backend:${BRANCH_NAME}
    env_file: .env.local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - backend


networks:
   backend:
    driver: bridge
    external: true
